# Generated by Django 3.0.8 on 2020-07-31 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0012_auto_20200731_2059'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_list',
            field=models.ManyToManyField(related_name='apis', to='user_dashboard.ApiList'),
        ),
    ]
