# Generated by Django 3.0.8 on 2020-07-31 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0012_auto_20200731_2059'),
        ('accounts', '0002_user_api_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_list',
            field=models.ManyToManyField(blank=True, related_name='apis', to='user_dashboard.ApiList'),
        ),
    ]
