# Generated by Django 3.0.8 on 2020-07-30 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0002_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='apiBox',
            new_name='ActiveApiList',
        ),
    ]
