# Generated by Django 3.0.8 on 2020-07-30 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0005_auto_20200730_0211'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveApiList',
        ),
    ]
