# Generated by Django 3.0.8 on 2020-07-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0006_delete_activeapilist'),
    ]

    operations = [
        migrations.AddField(
            model_name='apilist',
            name='stats',
            field=models.CharField(default='3hrs', max_length=255),
        ),
    ]
