# Generated by Django 3.0.8 on 2020-07-31 16:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_dashboard', '0008_activeapilist'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeapilist',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
