# Generated by Django 3.0.8 on 2020-07-31 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0011_auto_20200731_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeapilist',
            name='user',
        ),
        migrations.AlterField(
            model_name='apilist',
            name='stats',
            field=models.CharField(default='3req/hr', max_length=255),
        ),
    ]
